modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/TetraTheta/coeluria-core/issues"
license = "All Rights Reserved"

[[mods]]
modId = "coeluriacore"
version = "${version}"
displayName = "CoeluriaCore"
authors = "TetraTheta"
description = "Personal mod that enhances Minecraft experience"
logoFile = "assets/coeluriacore/icon.png"

[[dependencies.coeluriacore]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coeluriacore]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coeluriacore]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "coeluriacore.mixins.json"
